// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Spot struct {
	ID        int64        `db:"id" json:"id"`
	Latitude  int64        `db:"latitude" json:"latitude"`
	Longitude int64        `db:"longitude" json:"longitude"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}
