// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: spots.sql

package database

import (
	"context"
)

const getAllSpots = `-- name: GetAllSpots :many
SELECT id, latitude, longitude, created_at FROM spots
`

func (q *Queries) GetAllSpots(ctx context.Context) ([]Spot, error) {
	rows, err := q.db.QueryContext(ctx, getAllSpots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spot{}
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
